version: "3"

services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: cookdoc
      MYSQL_ROOT_PASSWORD: root0707
    ports:
      - 3307:3306
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - cooknet


  application:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    networks:
      - cooknet

volumes:
  db-data:

networks:
  cooknet:
